#!/usr/bin/env python3
"""
sync — Claude-powered API doc sync for Mintlify docs.

Reads an OpenAPI spec, finds all MDX files in the docs repo that reference
an operation via their `openapi:` frontmatter, and uses Claude to update
ParamField/ResponseField blocks while preserving all hand-crafted prose,
code examples, and configuration recipes.

Works with any OpenAPI spec — not just the parser API.

Usage:
    # Dry run — print diffs, write nothing
    uv run doc-sync --spec ../../parser/docs/openapi/v1.json --docs-root .. --dry-run

    # Apply to a single file
    uv run doc-sync --spec ../../parser/docs/openapi/v1.json --docs-root .. \\
        --file api-reference/parser/parse-document.mdx

    # Apply to all MDX files
    uv run doc-sync --spec ../../parser/docs/openapi/v1.json --docs-root ..

    # Sync + judge + revise if issues found
    uv run doc-sync --spec ../../parser/docs/openapi/v1.json --docs-root .. \\
        --source-root ../../parser --judge --revise
"""
from __future__ import annotations

import sys
from pathlib import Path

import click
from rich.console import Console

from doc_sync.spec import loader as load_spec
from doc_sync.mdx import loader as load_mdx
from doc_sync.enrichment import stubs as generate_stubs
from doc_sync.enrichment import enrich
from doc_sync.mdx import writer as write_mdx

console = Console()


@click.command()
@click.option(
    "--spec",
    required=True,
    type=click.Path(exists=True, dir_okay=False),
    help="Path to openapi.json (generated by `make export-spec`).",
)
@click.option(
    "--docs-root",
    required=True,
    type=click.Path(exists=True, file_okay=False),
    help="Root of the Mintlify docs repo (contains api-reference/).",
)
@click.option(
    "--file",
    "target_file",
    default=None,
    type=str,
    help="Process only this MDX file (relative to docs-root). Omit to process all.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Print diffs but do not write any files.",
)
@click.option(
    "--model",
    default=None,
    show_default=False,
    help=(
        "Claude model ID for generation. Defaults to 'claude-sonnet-4-6' (Anthropic API) or "
        "'us.anthropic.claude-opus-4-6-20250514-v1:0' (Bedrock)."
    ),
)
@click.option(
    "--bedrock",
    is_flag=True,
    default=False,
    help="Route requests via Amazon Bedrock using the current AWS credentials.",
)
@click.option(
    "--no-diff",
    is_flag=True,
    default=False,
    help="Suppress per-file diff output (only print summary).",
)
@click.option(
    "--judge",
    "run_judge",
    is_flag=True,
    default=False,
    help="Run LLM judge after enrichment to validate the updated doc against source code.",
)
@click.option(
    "--revise",
    is_flag=True,
    default=False,
    help=(
        "If the judge finds issues, run a second generator pass to fix them before writing. "
        "Requires --judge."
    ),
)
@click.option(
    "--source-root",
    default=None,
    type=click.Path(file_okay=False),
    help="Path to the API source repo root (used by the judge to read Rust source code).",
)
@click.option(
    "--judge-model",
    default=None,
    show_default=False,
    help=(
        "Claude model ID for the judge. Defaults to 'claude-opus-4-6' (Anthropic API) or "
        "'us.anthropic.claude-opus-4-6-20250514-v1:0' (Bedrock). "
        "Should be equal to or stronger than the generator model."
    ),
)
@click.option(
    "--fail-on-issues",
    is_flag=True,
    default=False,
    help="Exit with code 1 if the judge finds issues in any file. Useful for CI.",
)
def main(
    spec: str,
    docs_root: str,
    target_file: str | None,
    dry_run: bool,
    model: str | None,
    bedrock: bool,
    no_diff: bool,
    run_judge: bool,
    revise: bool,
    source_root: str | None,
    judge_model: str | None,
    fail_on_issues: bool,
) -> None:
    from doc_sync.enrichment.enrich import _BEDROCK_DEFAULT_MODEL
    from doc_sync.judge.judge import _DEFAULT_JUDGE_MODEL, _BEDROCK_JUDGE_MODEL

    if model is None:
        model = _BEDROCK_DEFAULT_MODEL if bedrock else "claude-sonnet-4-6"
    if judge_model is None:
        judge_model = _BEDROCK_JUDGE_MODEL if bedrock else _DEFAULT_JUDGE_MODEL

    spec_path = Path(spec).resolve()
    docs_path = Path(docs_root).resolve()
    source_path = Path(source_root).resolve() if source_root else None

    if revise and not run_judge:
        console.print("[red]--revise requires --judge.[/red]")
        raise SystemExit(1)

    if run_judge and source_path is None:
        console.print(
            "[yellow]⚠[/yellow] --judge is active but --source-root was not provided. "
            "The judge will receive spec context only (no Rust source code)."
        )

    # ── Step 1: Load spec ────────────────────────────────────────────────────
    console.rule("[bold blue]Step 1 — Loading OpenAPI spec")
    full_spec = load_spec.load(spec_path)
    operations = load_spec.index_operations(full_spec)
    schemas = load_spec.get_schemas(full_spec)
    console.print(
        f"  [green]✓[/green] Loaded spec with "
        f"[bold]{len(operations)}[/bold] operations and "
        f"[bold]{len(schemas)}[/bold] schemas"
    )

    # ── Step 2: Discover MDX files ───────────────────────────────────────────
    console.rule("[bold blue]Step 2 — Discovering MDX files")
    all_mdx = load_mdx.discover(docs_path)

    if target_file:
        target_path = (docs_path / target_file).resolve()
        all_mdx = [f for f in all_mdx if f.path.resolve() == target_path]
        if not all_mdx:
            console.print(f"[red]No MDX file with openapi: frontmatter found at {target_file}[/red]")
            raise SystemExit(1)

    console.print(f"  [green]✓[/green] Found [bold]{len(all_mdx)}[/bold] MDX file(s) with openapi: frontmatter")

    matched: list[load_mdx.MdxFile] = []
    for mdx_file in all_mdx:
        key = mdx_file.operation_key
        norm_key = mdx_file.operation_key_normalized
        resolved_key = key if key in operations else (norm_key if norm_key in operations else None)

        if resolved_key is not None:
            display = key if resolved_key == key else f"{key} [dim](matched via {resolved_key})[/dim]"
            console.print(f"    [cyan]✓[/cyan] {mdx_file.path.name}  →  {display}")
            mdx_file.operation_key = resolved_key
            matched.append(mdx_file)
        else:
            console.print(
                f"    [yellow]⚠[/yellow] {mdx_file.path.name}  "
                f"[dim]operation '{key}' not found in spec — skipping[/dim]"
            )

    if not matched:
        console.print("[yellow]No files matched spec operations. Nothing to do.[/yellow]")
        raise SystemExit(0)

    # ── Step 3: Generate Mintlify stubs (reference only) ─────────────────────
    console.rule("[bold blue]Step 3 — Generating Mintlify stubs (reference)")
    stubs = generate_stubs.generate(spec_path)
    if stubs:
        console.print(f"  [green]✓[/green] Generated [bold]{len(stubs)}[/bold] stub(s) from spec")
    else:
        console.print("  [dim]ℹ Stubs not available (npx/scraper not found) — continuing without[/dim]")

    # ── Step 4: Claude enrichment pass ──────────────────────────────────────
    console.rule("[bold blue]Step 4 — Enriching MDX with Claude")
    results: list[write_mdx.FileResult] = []

    for mdx_file in matched:
        operation_data = operations[mdx_file.operation_key]
        stub = stubs.get(mdx_file.operation_key, "")

        source_mdx = mdx_file.raw_text
        if stub:
            source_mdx = (
                source_mdx
                + "\n\n<!-- MINTLIFY_STUB_REFERENCE (do not include in output) -->\n"
                + stub
            )

        console.print(f"  [cyan]→[/cyan] {mdx_file.path.name}  ({mdx_file.operation_key})")
        try:
            updated = enrich.enrich_file(
                mdx_raw=source_mdx,
                operation=operation_data,
                schemas=schemas,
                model=model,
                bedrock=bedrock,
            )
        except Exception as e:
            console.print(f"    [red]✗ Claude call failed: {e}[/red]")
            updated = mdx_file.raw_text

        results.append(
            write_mdx.FileResult(
                path=mdx_file.path,
                original=mdx_file.raw_text,
                updated=updated,
                operation_key=mdx_file.operation_key,
            )
        )

    # ── Step 5: Judge pass (optional) ────────────────────────────────────────
    if run_judge:
        console.rule("[bold blue]Step 5 — LLM Judge")
        from doc_sync.judge import judge as judge_module
        from doc_sync.judge.source_collector import collect_source_context

        any_failed = False

        for result in results:
            operation_data = operations[result.operation_key]
            console.print(f"  [cyan]⚖[/cyan] Judging {result.path.name}  ({result.operation_key})")

            # Collect Rust source context
            source_context = ""
            if source_path:
                source_context = collect_source_context(result.operation_key, source_path)
                if source_context:
                    console.print(f"    [dim]Source context collected ({len(source_context)} chars)[/dim]")
                else:
                    console.print("    [dim]No source context found — judging from spec only[/dim]")

            try:
                jr = judge_module.judge_file(
                    mdx_content=result.updated,
                    operation=operation_data,
                    schemas=schemas,
                    source_context=source_context,
                    model=judge_model,
                    bedrock=bedrock,
                )
            except Exception as e:
                console.print(f"    [red]✗ Judge call failed: {e}[/red]")
                continue

            result.judge_result = jr

            if jr.passed:
                console.print(f"    [green]✓ PASS[/green]  {jr.summary}")
            else:
                any_failed = True
                console.print(f"    [red]✗ FAIL[/red]  {jr.summary}")
                for issue in jr.critical_issues:
                    console.print(f"      [red]↳ [CRITICAL][/red] {issue.location}: {issue.fix}")
                for issue in jr.minor_issues:
                    console.print(f"      [yellow]↳ [minor][/yellow] {issue.location}: {issue.fix}")

            # ── Step 5b: Revise if issues found ──────────────────────────────
            if revise and not jr.passed and jr.issues:
                console.print(f"    [cyan]↻[/cyan] Revising with critique ({len(jr.issues)} issue(s))...")
                try:
                    revised = enrich.enrich_with_critique(
                        mdx_raw=result.updated,
                        operation=operation_data,
                        schemas=schemas,
                        issues=jr.issues,
                        model=model,
                        bedrock=bedrock,
                    )
                    result.updated = revised
                    console.print("    [green]✓[/green] Revision complete")

                    # Confirm with a second judge pass
                    console.print("    [cyan]⚖[/cyan] Re-judging revised output...")
                    jr2 = judge_module.judge_file(
                        mdx_content=revised,
                        operation=operation_data,
                        schemas=schemas,
                        source_context=source_context,
                        model=judge_model,
                        bedrock=bedrock,
                    )
                    result.judge_result = jr2
                    if jr2.passed:
                        any_failed = False
                        console.print(f"    [green]✓ PASS after revision[/green]  {jr2.summary}")
                    else:
                        console.print(f"    [yellow]⚠ Still failing after revision[/yellow]  {jr2.summary}")

                except Exception as e:
                    console.print(f"    [red]✗ Revision call failed: {e}[/red]")

        if fail_on_issues and any_failed:
            console.print("\n[red]Judge found issues — exiting with code 1 (--fail-on-issues).[/red]")
            # Write step runs before exit so diffs are visible
    else:
        any_failed = False

    # ── Step 6: Write / diff ─────────────────────────────────────────────────
    step_num = "6" if run_judge else "5"
    console.rule(f"[bold blue]Step {step_num} — Writing results")
    write_mdx.write_results(results, dry_run=dry_run, show_diff=not no_diff)

    if dry_run:
        console.print("\n[dim]Dry run — no files were modified.[/dim]")

    if run_judge and fail_on_issues and any_failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
